version: '2'
services:

  mysql:
    image: hypriot/rpi-mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - ./mysql:/var/lib/mysql

  bookstack:
    image: budrom/rpi-bookstack:latest
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - ./uploads:/var/www/BookStack/public/uploads
    ports:
    - "80:80"
